### ISSUE TITLE
broken compilation

### ISSUE THREAD

**Issue by adamkrellenstein** [ethereum/serpent#33]
With `ethereum-serpent==1.78`:

```
> serpent compile 'return(msg.data[0] * 2)'
Error (file "main", line 1, char 10): Invalid object member (ie. a foo.bar not mapped to anything)
Traceback (most recent call last):
  File "/usr/bin/serpent", line 9, in <module>
    load_entry_point('ethereum-serpent==1.7.8', 'console_scripts', 'serpent')()
  File "/usr/bin/serpent.py", line 197, in main
    o = globals()[cmd](*args)
  File "/usr/bin/serpent.py", line 74, in <lambda>
    compile = lambda x: pyext.compile(x)
Exception: Error (file "main", line 1, char 10): Invalid object member (ie. a foo.bar not mapped to anything)
```

**Comment by vbuterin** [comment]
Yeah, msg.data is deprecated. If you still want it, do
return(calldataload(0) * 2)

**Comment by adamkrellenstein** [comment]
Got it. Thanks. (Feel free to close the issue.)
