### ISSUE TITLE
compilation error on cyberdyne market example

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/serpent#85]
With serpent develop branch:

```
$ serpent compile examples/cyberdyne/market.se
Error (file "main", line 0, char 4294967295): Bad signature: _
Traceback (most recent call last):
  File "/Users/mids/.virtualenvs/serpent/bin/serpent", line 9, in <module>
    load_entry_point('ethereum-serpent==2.0.0', 'console_scripts', 'serpent')()
  File "/Users/mids/.virtualenvs/serpent/bin/serpent.py", line 202, in main
    o = globals()[cmd](*args, **kwargs)
  File "/Users/mids/.virtualenvs/serpent/bin/serpent.py", line 78, in <lambda>
    compile = lambda x: pyext.compile(strtobytes(x))
Exception: Error (file "main", line 0, char 4294967295): Bad signature: _
```

**Comment by jorisbontje** [comment]
`extern` signatures in `examples/cyberdyne/market.se` need to be updated to the new format:

```
extern heap: [pop:[]:int256, push:[int256]:_, set_owner:[int256]:_, size:[]:int256, top:[]:int256]
extern subcurrency: [balance:[int256]:int256, change_ownership:[int256]:_, issue:[int256,int256]:_, last_tx:[]:int256[], send:[int256,int256]:int256]
```
